sudo: false
language: node_js
env:
  - NODE_ENV=dev
node_js:
  - "stable"
  - "4.2"
  - "0.12"
  - "0.10"
before_install: 
    - 'if [ "${TRAVIS_NODE_VERSION}" == "0.10" ]; then npm install -g npm@2 ; fi'
notifications:
  irc: "irc.GameSurge.Net#tennudev"
